### ISSUE TITLE
Duplication BUG

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#855]
This bug is appearing in many places site-wide. See:

- [x] Duplicate methods in sidebar https://github.com/participedia/usersnaps/issues/200
- [x] Duplicate components in sidebar https://github.com/participedia/usersnaps/issues/199
- [x] Duplicate location in sidebar https://github.com/participedia/usersnaps/issues/163
- [x] Duplicate bookmarks on profile page https://github.com/participedia/usersnaps/issues/167

**Comment by jesicarson** [comment]
- Duplicate method in results after editing (original AND new edited version shown in results) https://github.com/participedia/usersnaps/issues/210

**Comment by ascott** [comment]
fix for the methods/components duplication issues https://github.com/participedia/frontend/pull/913
